sudo: required
services:
  - docker
before_script:
  - docker build -t pascalgrimaud/tomcat .
script:
  - docker run -d -p 18080:8080 --name=tomcat -e TOMCAT_PASS="pgrimaud" pascalgrimaud/tomcat ; sleep 10
  - docker logs tomcat
  - curl -I http://localhost:18080 | grep "HTTP/1.1 200 OK"
